server.port=8080
logging.level.org.springframework.web= DEBUG

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://localhost:5000/swen2-db
spring.datasource.username=postgres
spring.datasource.password=mysecret-d

greeter.language=DE